# Dumont Connector - WC Plugin Sample Configuration (Wikipedia)

# Indexing provider (options: turing, elasticsearch, solr)
dumont.indexing.provider=turing

# Turing ES connection
turing.url=http://localhost:2700
turing.apiKey=3777564ba45c4470a02769b90

# Server port
server.port=30132

# H2 Console (for embedded H2 database)
spring.h2.console.enabled=true

# Logging configuration
logging.config=classpath:logback-spring.xml
logging.level.com.viglet=DEBUG
logging.level.org.springframework=DEBUG
logging.level.org.apache=INFO
